### ISSUE TITLE
Item Frames & Armor Stands not properly logged

### ISSUE THREAD

**Issue by Puremin0rez** [bob7l/HawkReloaded#44]
Item frames will log the placement and breaking of the frame itself, but not the item added or removed from the frame.

Armor stands are not logged at all. Not even sure there are proper inventory events for armor stands yet?

**Comment by RoboMWM** [comment]
Considering you seem to be returning to activity on this, will this be fixed? Currently trying to find a block logger that's open source and compatible with 1.8 items - the only one is CoreProtect, but it's closed source and the author is moving to Sponge.

**Comment by bob7l** [comment]
Yeah i'll fix it

**Comment by bob7l** [comment]
I'll commit the fix (Plus more) when i'm done working on my itemserializer. So instead of just the ID of the item, hawkeye will log every "api visible" aspect of the item. I say api visible because we'll still ignore things like custom attributes (Although i believe 1.9 added attribute api! Thanks spigot!)

**Comment by RoboMWM** [comment]
Cool, I'm fine with remaining within the bounds of the bukkit/spigot/paper API. Thank you for resurrecting this project! Was about to lose hope on finding a properly maintained block logger for Spigot.

**Comment by bob7l** [comment]
The item-serializer works flawlessy! This will help expand our logging capabilities massively and is even future proofed. 

The next thing i need to figure out is whether or not an event is fired in 1.8 when an item is removed from an item frame. I'll also have to make a new action type (Probably frame-extract/frame-insert)

**Comment by bob7l** [comment]
I've fixed the itemframes and made the logging much better. They'll also utilize the new item serializer

I'm not sure whether or not it'll work with previous builds, but i don't see why not. 

Post here if you have an issue with it. 

On a side note, i'll add armorstand logging soon considering they now have API and 1.8 is much more stable.

**Comment by Puremin0rez** [comment]
Glad to hear :)

**Comment by Puremin0rez** [comment]
@bob7l 
This might not be the best place to submit this issue, but player heads also do not rollback properly if you'd like to look into that.

**Comment by bob7l** [comment]
@Puremin0rez 
Yeah i'm aware of that. The only issue is then i'll have to implement block-meta for block related entries rather then just using primitive variables {block-id : block-data}. So i'd have to recode a pretty big portion of the plugin considering it's all hardcoded for just two primitive block values. But that'd also allow for extremely simple expansion / updating at a cost of some performance loss. We'll defiantly have to see because it seems minecraft is adding more and more tile entities with important data attached to them. The meta would probably follow the same layout as the new inventory serializer.

**Comment by bob7l** [comment]
@RoboMWM 

> Cool, I'm fine with remaining within the bounds of the bukkit/spigot/paper API.

I'll most likely turn HawkEye modular soon to allow for support for sponge,bukkit, and so on. I was planning on adding sponge support sooner, but sponges API has been extremely dynamic and hard to keep up with.

**Comment by bob7l** [comment]
I'm going to add rebuild support soon for this enhancement soon aswell.
